### ISSUE TITLE
Standardize the UI for the leaflet pop-up on mobile and desktop

### ISSUE THREAD

**Issue by imohkay** [klpdotorg/dubdubdub#380] opened 2015-01-07 10:03 UTC
Sub-issue for #382

1. Differentiate the close button (maybe grey and the others blue) and knock off the close on the top right

2. Avoid different code and UI and mobile and desktop

If possible, I'd like to keep the mobile layout with the pop-up fixed to the bottom for desktop as well. We can give more padding on the left and right so it doesn't fill the whole width on desktop. Let me know if this is fine. We'll need to ensure z-index of the fixed div is fine, in case of short height viewports, in this case.

**Comment by imohkay** [comment] 2015-01-07 10:03
@batpad let me know if this fine.

**Comment by batpad** [comment] 2015-01-07 10:04
@imohkay this I would just leave as is if possible .. can look at what you've got in mind, but I think the current setup actually works okay - is some slightly different code, but in some sense unavoidable. Anyways, can discuss.

**Comment by imohkay** [comment] 2015-01-16 15:10
@batpad could you add close functionality to the grey close button and assign back to me when done? on the frontend refactor branch.

**Comment by imohkay** [comment] 2015-02-09 15:47
@batpad hey... right now, map is kinda broken on mobile (or if you resize the window to small and refresh page)... the older code seems to be still there in the JS... could you comment out the conditional code and I'll test the popup and see if it works on mobile? then we can knock off that code...

**Comment by imohkay** [comment] 2015-02-09 15:53
@batpad found another small bug... on smaller screens, when you click More Info on the map pop-up, it goes to the school page, but scrolls the accordion to the top of the viewport, so you don't see the map and that content unless you scroll up... weird situation.

**Comment by batpad** [comment] 2015-02-10 11:29
@imohkay did the following and pushed to develop:

 - removed conditional popup code for mobile in map.js
 - made it so that it doesn't scroll to the default tab that opens on school page on mobile
 - added some animation to the scrolling to top of accordion ..

Please check and let me know if that all works as intended? Thanks.

**Comment by imohkay** [comment] 2015-02-10 16:03
@batpad it looks very handzome.

**Comment by batpad** [comment] 2015-02-13 08:48
@imohkay this is fixed? closing.

**Closed by batpad** 2015-02-13 08:48 UTC
Labels: frontend-refactor
